centos_build:
  stage: build
  tags:
    - centos
  artifacts:
    paths:
      - ./build/src/mem
  script:
    - ./build.sh $CI_PROJECT_DIR $CI_SERVER_NAME $CI_COMMIT_REF_NAME

centos_run:
  stage: test
  tags:
    - centos
  dependencies:
    - centos_build
  script:
    - ./build/src/mem

mac_build:
  stage: build
  tags:
    - mac
  artifacts:
    paths:
      - ./build/src/mem
  script:
    - ./build.sh $CI_PROJECT_DIR $CI_SERVER_NAME $CI_COMMIT_REF_NAME

mac_run:
  stage: test
  tags:
    - mac
  dependencies:
    - mac_build
  script:
    - export DYLD_LIBRARY_PATH="$DYLD_LIBRARY_PATH:/Users/jenkins/openfpm_dependencies/openfpm_devices/BOOST/lib" && ./build/src/mem

ubuntu_build:
  stage: build
  tags:
    - ubuntu
  artifacts:
    paths:
      - ./build/src/mem
  script:
    - ./build.sh $CI_PROJECT_DIR $CI_SERVER_NAME $CI_COMMIT_REF_NAME

ubuntu_run:
  stage: test
  tags:
    - ubuntu
  dependencies:
    - ubuntu_build
  script:
    - ./build/src/mem

