centos_build:
  stage: build
  tags:
    - centos
  artifacts:
    paths:
      - ./build/src/mem
  script:
    - ./build.sh $CI_PROJECT_DIR $CI_SERVER_NAME

centos_run:
  stage: test
  tags:
    - centos
  dependencies:
    - centos_build
  script:
    - ./build/src/mem
    - ./success.sh 2 centos openfpm_devices

mac_build:
  stage: build
  tags:
    - mac
  artifacts:
    paths:
      - ./build/src/mem
  script:
    - ./build.sh $CI_PROJECT_DIR $CI_SERVER_NAME

mac_run:
  stage: test
  tags:
    - mac
  dependencies:
    - mac_build
  script:
    - ./build/src/mem
    - ./success.sh 2 mac openfpm_devices

ubuntu_build:
  stage: build
  tags:
    - ubuntu
  artifacts:
    paths:
      - ./build/src/mem
  script:
    - ./build.sh $CI_PROJECT_DIR $CI_SERVER_NAME

ubuntu_run:
  stage: test
  tags:
    - ubuntu
  dependencies:
    - ubuntu_build
  script:
    - ./build/src/mem
    - ./success.sh 2 ubuntu openfpm_devices

